### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by savan8192** [caroljmcdonald/mapr-streams-spark#2]
Hi,

I am trying to run the sample program and I am faced with the following error and no fix found online seems to work for me. Any help will be much appreciated.

Thanks in advance.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer

at com.streamskafka.example.MsgProducer.configureProducer(MsgProducer.java:67)

at com.streamskafka.example.MsgProducer.main(MsgProducer.java:30)

Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.KafkaProducer

at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 

... 2 more
```

**Comment by caroljmcdonald** [comment]
The pom file probably needs updating . Are you using maven?

**Comment by savan8192** [comment]
Hi Carol, thanks for your reply. Yes, I built it using maven. I was using MapR 6.1. Just for the sake of trying, I will try MapR 5.2 (instead of 6.1) and see if that's any good.

Update: I am not getting the error with MapR 5.2 I used the same jar file.

Another update: I am still getting the error for spark commands and consumer commands. I will have a go at updating POM file.

Thankns
